[tool.black]
line-length = 100
target-version = ["py311"]
include = "\.(py|pyi)$"
exclude = "(\.venv|venv|node_modules|dist|build|.git|alembic)"

[tool.ruff]
# Keep in sync with ruff.toml if both exist
line-length = 100

[tool.pytest.ini_options]
addopts = "-q"
pythonpath = ["backend/app"]
